package constant

const (
	MsgInvalidInput       = "Invalid input"
	MsgInvalidIDFormat    = "Invalid ID format"
	MsgUnauthorized       = "Unauthorized"
	MsgInvalidTokenClaim  = "Invalid token claim"
	MsgAuthHeaderRequired = "Authorization header required"
	MsgInvalidAuthFormat  = "Invalid authorization format"
	MsgInvalidToken       = "Invalid or expired token"
	MsgNoUpdatesProvided  = "No updates provided"
	MsgSearchRequired     = "Search keyword is required"
	MsgRateLimitExceeded  = "Too many requests, please try again later"
	MsgInternalError      = "Internal server error"

	MsgAdminRegisterOK    = "Admin registered successfully"
	MsgAdminRegisterFail  = "Admin registration failed"
	MsgAdminLoginOK       = "Login success"
	MsgAdminLoginFail     = "Login failed"
	MsgAdminUpdateOK      = "Admin updated successfully"
	MsgAdminUpdateFail    = "Admin update failed"
	MsgAdminLogoutOK      = "Admin logged out successfully"
	MsgAdminProfileOK     = "Admin profile retrieved successfully"
	MsgAdminNotFound      = "Admin not found"

	MsgUserRegisterOK     = "User registered successfully"
	MsgUserRegisterFail   = "User registration failed"
	MsgUserLoginOK        = "Login success"
	MsgUserLoginFail      = "Login failed"
	MsgUserGoogleLoginOK  = "Google login success"
	MsgUserGoogleLoginFail = "Google login failed"
	MsgUserUpdateOK       = "User updated successfully"
	MsgUserUpdateFail     = "User update failed"
	MsgUserLogoutOK       = "User logged out successfully"
	MsgUserProfileOK      = "User profile retrieved successfully"
	MsgUserNotFound       = "User not found"

	MsgCategoryCreateOK   = "Category created successfully"
	MsgCategoryCreateFail = "Failed to create category"
	MsgCategoryListOK     = "Categories retrieved successfully"
	MsgCategoryListFail   = "Failed to fetch categories"
	MsgCategoryGetOK      = "Category retrieved successfully"
	MsgCategoryNotFound   = "Category not found"
	MsgCategoryUpdateOK   = "Category updated successfully"
	MsgCategoryUpdateFail = "Failed to update category"
	MsgCategoryDeleteOK   = "Category deleted successfully"
	MsgCategoryDeleteFail = "Failed to delete category"
	MsgCategorySearchOK   = "Categories found successfully"
	MsgCategorySearchFail = "Failed to search categories"

	MsgAudioCreateOK      = "Audio created successfully"
	MsgAudioCreateFail    = "Failed to create audio"
	MsgAudioListOK        = "Audios retrieved successfully"
	MsgAudioListFail      = "Failed to fetch audios"
	MsgAudioGetOK         = "Audio retrieved successfully"
	MsgAudioNotFound      = "Audio not found"
	MsgAudioUpdateOK      = "Audio updated successfully"
	MsgAudioUpdateFail    = "Failed to update audio"
	MsgAudioDeleteOK      = "Audio deleted successfully"
	MsgAudioDeleteFail    = "Failed to delete audio"
	MsgAudioSearchOK      = "Audios found successfully"
	MsgAudioSearchFail    = "Failed to search audios"

	MsgPlaylistCreateOK   = "Playlist created successfully"
	MsgPlaylistCreateFail = "Failed to create playlist"
	MsgPlaylistListOK     = "Playlists retrieved"
	MsgPlaylistListFail   = "Failed to fetch playlists"
	MsgPlaylistGetOK      = "Playlist detail retrieved"
	MsgPlaylistNotFound   = "Playlist not found"
	MsgPlaylistUpdateOK   = "Playlist updated successfully"
	MsgPlaylistUpdateFail = "Failed to update playlist"
	MsgPlaylistDeleteOK   = "Playlist deleted successfully"
	MsgPlaylistDeleteFail = "Failed to delete playlist"
	MsgPlaylistSearchOK   = "Playlists found"
	MsgPlaylistSearchFail = "Failed to search playlists"
	MsgPlaylistShareOK    = "Playlist shared successfully"
	MsgPlaylistShareFail  = "Failed to share playlist"
	MsgPlaylistAddAudioOK   = "Audio added successfully"
	MsgPlaylistAddAudioFail = "Failed to add audio"
	MsgPlaylistRemoveAudioOK   = "Audio removed from playlist"
	MsgPlaylistRemoveAudioFail = "Failed to remove audio"
	MsgPlaylistFull       = "Playlist is full (max 20 audios)"
	MsgAudioAlreadyInPlaylist = "Audio already in playlist"

	MsgLikeOK             = "Liked successfully"
	MsgLikeFail           = "Failed to like"
	MsgUnlikeOK           = "Unliked successfully"
	MsgUnlikeFail         = "Failed to unlike"
	MsgLikeListOK         = "Likes retrieved"
	MsgLikeListFail       = "Failed to fetch likes"
	MsgAlreadyLiked       = "Already liked"
	MsgLikeNotFound       = "Like not found"

	MsgHistoryListOK      = "Play history retrieved"
	MsgHistoryListFail    = "Failed to fetch play history"
	MsgHistoryDeleteOK    = "History deleted successfully"
	MsgHistoryDeleteFail  = "Failed to delete history"
	MsgHistoryClearOK     = "All history cleared successfully"
	MsgHistoryClearFail   = "Failed to clear history"
	MsgInvalidAudioID     = "Invalid Audio ID"

	MsgDirCreateFail      = "Failed to create directory"
	MsgFileUploadFail     = "Failed to upload image"

	MsgOTPSendOK          = "OTP sent successfully"
	MsgOTPSendFail        = "Failed to send OTP"
	MsgOTPVerifyOK        = "Email verified successfully"
	MsgOTPVerifyFail      = "Invalid or expired OTP"
	MsgOTPRateLimit       = "Too many OTP requests, please wait"
	MsgOTPExpired         = "OTP has expired"
	MsgOTPInvalid         = "Invalid OTP code"
	MsgEmailNotVerified   = "Email not verified, please verify your email first"

	MsgGoogleLinkOK       = "Google account linked successfully"
	MsgGoogleLinkFail     = "Failed to link Google account"
	MsgGoogleUnlinkOK     = "Google account unlinked successfully"
	MsgGoogleUnlinkFail   = "Failed to unlink Google account"
	MsgGoogleAlreadyLinked = "Google account already linked"
	MsgGoogleNotLinked    = "No Google account linked"
	MsgGoogleNoPassword   = "Cannot unlink Google without setting a password first"
	MsgGoogleEmailLocked  = "Email cannot be changed for Google-linked accounts"

	MsgRecommendPopularOK      = "Popular content retrieved"
	MsgRecommendMostListenedOK = "Most listened content retrieved"
	MsgRecommendByArtistOK     = "Content by artist retrieved"
	MsgRecommendSimilarOK      = "Similar content retrieved"
	MsgRecommendQuickPickOK    = "Quick pick content retrieved"
	MsgRecommendOnboardingOK   = "Onboarding content retrieved"
	MsgRecommendPersonalizedOK = "Personalized content retrieved"
	MsgRecommendFail           = "Failed to get recommendations"
	MsgArtistRequired          = "Artist name is required"

	MsgColorExtractFail   = "Failed to extract dominant color"
	MsgScoreRecalcOK      = "Score recalculation completed"
	MsgScoreRecalcFail    = "Score recalculation failed"

	MsgBookmarkCreateOK   = "Bookmark created successfully"
	MsgBookmarkCreateFail = "Failed to create bookmark"
	MsgBookmarkListOK     = "Bookmarks retrieved"
	MsgBookmarkListFail   = "Failed to fetch bookmarks"
	MsgBookmarkDeleteOK   = "Bookmark deleted successfully"
	MsgBookmarkDeleteFail = "Failed to delete bookmark"

	MsgNotificationListOK         = "Notifications retrieved"
	MsgNotificationListFail       = "Failed to fetch notifications"
	MsgNotificationReadOK         = "Notification marked as read"
	MsgNotificationReadFail       = "Failed to mark notification"
	MsgNotificationReadAllOK      = "All notifications marked as read"
	MsgNotificationCountOK        = "Unread count retrieved"
	MsgNotificationSettingOK      = "Notification settings retrieved"
	MsgNotificationSettingFail    = "Failed to get notification settings"
	MsgNotificationSettingUpdateOK = "Notification settings updated"

	MsgProgressUpdateOK   = "Progress updated"
	MsgProgressUpdateFail = "Failed to update progress"
	MsgProgressGetOK      = "Progress retrieved"
	MsgProgressNotFound   = "Progress not found"
	MsgProgressListOK     = "Progress list retrieved"
	MsgProgressListFail   = "Failed to fetch progress"

	MsgDownloadOK         = "Download recorded"
	MsgDownloadFail       = "Failed to record download"
	MsgDownloadListOK     = "Downloads retrieved"
	MsgDownloadListFail   = "Failed to fetch downloads"
	MsgDownloadDeleteOK   = "Download deleted"
	MsgDownloadDeleteFail = "Failed to delete download"
	MsgDownloadStorageOK  = "Storage usage retrieved"
	MsgDownloadSmartOK    = "Smart download suggestions retrieved"
	MsgDownloadSmartFail  = "Failed to get smart downloads"

	MsgStatRecordOK    = "Stat recorded"
	MsgStatRecordFail  = "Failed to record stat"
	MsgStatRecapOK     = "Stats recap retrieved"
	MsgStatRecapFail   = "Failed to get stats recap"

	MsgClipCreateOK   = "Clip created successfully"
	MsgClipCreateFail = "Failed to create clip"
	MsgClipListOK     = "Clips retrieved"
	MsgClipListFail   = "Failed to fetch clips"
	MsgClipGetOK      = "Clip retrieved"
	MsgClipNotFound   = "Clip not found"
	MsgClipDeleteOK   = "Clip deleted"
	MsgClipDeleteFail = "Failed to delete clip"

	MsgEventCreateOK      = "Event created successfully"
	MsgEventCreateFail    = "Failed to create event"
	MsgEventListOK        = "Events retrieved"
	MsgEventListFail      = "Failed to fetch events"
	MsgEventGetOK         = "Event retrieved"
	MsgEventNotFound      = "Event not found"
	MsgEventUpdateOK      = "Event updated successfully"
	MsgEventUpdateFail    = "Failed to update event"
	MsgEventDeleteOK      = "Event deleted successfully"
	MsgEventDeleteFail    = "Failed to delete event"
	MsgEventRSVPOK        = "RSVP confirmed"
	MsgEventRSVPFail      = "Failed to RSVP"
	MsgEventRSVPCancelOK  = "RSVP cancelled"
	MsgEventRSVPCancelFail = "Failed to cancel RSVP"
	MsgEventRSVPListOK    = "RSVPs retrieved"
	MsgEventRSVPListFail  = "Failed to fetch RSVPs"

	MsgPreferenceGetOK      = "Preferences retrieved"
	MsgPreferenceUpdateOK   = "Preferences updated"
	MsgPreferenceUpdateFail = "Failed to update preferences"

	MsgSeriesCreateOK      = "Series created successfully"
	MsgSeriesCreateFail    = "Failed to create series"
	MsgSeriesListOK        = "Series retrieved"
	MsgSeriesListFail      = "Failed to fetch series"
	MsgSeriesGetOK         = "Series retrieved"
	MsgSeriesNotFound      = "Series not found"
	MsgSeriesUpdateOK      = "Series updated successfully"
	MsgSeriesUpdateFail    = "Failed to update series"
	MsgSeriesDeleteOK      = "Series deleted successfully"
	MsgSeriesDeleteFail    = "Failed to delete series"
	MsgSeriesItemAddOK     = "Item added to series"
	MsgSeriesItemAddFail   = "Failed to add item to series"
	MsgSeriesItemRemoveOK  = "Item removed from series"
	MsgSeriesItemRemoveFail = "Failed to remove item from series"
	MsgSeriesSearchOK      = "Series found"
	MsgSeriesSearchFail    = "Failed to search series"

	MsgVoteOK         = "Vote recorded"
	MsgVoteFail       = "Failed to vote"
	MsgUnvoteOK       = "Vote removed"
	MsgUnvoteFail     = "Failed to unvote"
	MsgVoteStatusOK   = "Vote status retrieved"
	MsgRankingWeeklyOK  = "Weekly ranking retrieved"
	MsgRankingMonthlyOK = "Monthly ranking retrieved"
	MsgRankingFail      = "Failed to get ranking"

	MsgResumeUpdateOK   = "Resume state updated"
	MsgResumeUpdateFail = "Failed to update resume"
	MsgResumeGetOK      = "Resume state retrieved"
	MsgResumeNotFound   = "No resume state found"

	MsgShareOK   = "Share link generated"
	MsgShareFail = "Failed to generate share link"

	MsgFavoriteArtistAddOK      = "Artist added to favorites"
	MsgFavoriteArtistAddFail    = "Failed to add favorite artist"
	MsgFavoriteArtistRemoveOK   = "Artist removed from favorites"
	MsgFavoriteArtistRemoveFail = "Failed to remove favorite artist"
	MsgFavoriteArtistListOK     = "Favorite artists retrieved"
	MsgFavoriteArtistListFail   = "Failed to fetch favorite artists"

	MsgLocationUpdateOK   = "Location updated"
	MsgLocationUpdateFail = "Failed to update location"
	MsgLocationGetOK      = "Location retrieved"
	MsgLocationNotFound   = "Location not found"

	MsgCollabAddOK         = "Collaborator added"
	MsgCollabAddFail       = "Failed to add collaborator"
	MsgCollabRemoveOK      = "Collaborator removed"
	MsgCollabRemoveFail    = "Failed to remove collaborator"
	MsgCollabListOK        = "Collaborators retrieved"
	MsgCollabListFail      = "Failed to fetch collaborators"
	MsgCollabContributeOK  = "Audio contributed"
	MsgCollabContributeFail = "Failed to contribute audio"
	MsgCollabJoinOK        = "Joined playlist"
	MsgCollabJoinFail      = "Failed to join playlist"

	MsgRecommendLocationOK   = "Location-based content retrieved"
	MsgRecommendTimeBasedOK  = "Time-based content retrieved"
)
