package constant

const (
	MsgInvalidInput       = "Invalid input"
	MsgInvalidIDFormat    = "Invalid ID format"
	MsgUnauthorized       = "Unauthorized"
	MsgInvalidTokenClaim  = "Invalid token claim"
	MsgAuthHeaderRequired = "Authorization header required"
	MsgInvalidAuthFormat  = "Invalid authorization format"
	MsgInvalidToken       = "Invalid or expired token"
	MsgNoUpdatesProvided  = "No updates provided"
	MsgSearchRequired     = "Search keyword is required"
	MsgRateLimitExceeded  = "Too many requests, please try again later"
	MsgInternalError      = "Internal server error"

	MsgAdminRegisterOK    = "Admin registered successfully"
	MsgAdminRegisterFail  = "Admin registration failed"
	MsgAdminLoginOK       = "Login success"
	MsgAdminLoginFail     = "Login failed"
	MsgAdminUpdateOK      = "Admin updated successfully"
	MsgAdminUpdateFail    = "Admin update failed"
	MsgAdminLogoutOK      = "Admin logged out successfully"
	MsgAdminProfileOK     = "Admin profile retrieved successfully"
	MsgAdminNotFound      = "Admin not found"

	MsgUserRegisterOK     = "User registered successfully"
	MsgUserRegisterFail   = "User registration failed"
	MsgUserLoginOK        = "Login success"
	MsgUserLoginFail      = "Login failed"
	MsgUserGoogleLoginOK  = "Google login success"
	MsgUserGoogleLoginFail = "Google login failed"
	MsgUserUpdateOK       = "User updated successfully"
	MsgUserUpdateFail     = "User update failed"
	MsgUserLogoutOK       = "User logged out successfully"
	MsgUserProfileOK      = "User profile retrieved successfully"
	MsgUserNotFound       = "User not found"

	MsgCategoryCreateOK   = "Category created successfully"
	MsgCategoryCreateFail = "Failed to create category"
	MsgCategoryListOK     = "Categories retrieved successfully"
	MsgCategoryListFail   = "Failed to fetch categories"
	MsgCategoryGetOK      = "Category retrieved successfully"
	MsgCategoryNotFound   = "Category not found"
	MsgCategoryUpdateOK   = "Category updated successfully"
	MsgCategoryUpdateFail = "Failed to update category"
	MsgCategoryDeleteOK   = "Category deleted successfully"
	MsgCategoryDeleteFail = "Failed to delete category"
	MsgCategorySearchOK   = "Categories found successfully"
	MsgCategorySearchFail = "Failed to search categories"

	MsgAudioCreateOK      = "Audio created successfully"
	MsgAudioCreateFail    = "Failed to create audio"
	MsgAudioListOK        = "Audios retrieved successfully"
	MsgAudioListFail      = "Failed to fetch audios"
	MsgAudioGetOK         = "Audio retrieved successfully"
	MsgAudioNotFound      = "Audio not found"
	MsgAudioUpdateOK      = "Audio updated successfully"
	MsgAudioUpdateFail    = "Failed to update audio"
	MsgAudioDeleteOK      = "Audio deleted successfully"
	MsgAudioDeleteFail    = "Failed to delete audio"
	MsgAudioSearchOK      = "Audios found successfully"
	MsgAudioSearchFail    = "Failed to search audios"

	MsgPlaylistCreateOK   = "Playlist created successfully"
	MsgPlaylistCreateFail = "Failed to create playlist"
	MsgPlaylistListOK     = "Playlists retrieved"
	MsgPlaylistListFail   = "Failed to fetch playlists"
	MsgPlaylistGetOK      = "Playlist detail retrieved"
	MsgPlaylistNotFound   = "Playlist not found"
	MsgPlaylistSearchOK   = "Playlists found"
	MsgPlaylistSearchFail = "Failed to search playlists"
	MsgPlaylistAddAudioOK   = "Audio added successfully"
	MsgPlaylistAddAudioFail = "Failed to add audio"
	MsgPlaylistFull       = "Playlist is full (max 20 audios)"
	MsgAudioAlreadyInPlaylist = "Audio already in playlist"

	MsgLikeOK             = "Audio liked successfully"
	MsgLikeFail           = "Failed to like audio"
	MsgUnlikeOK           = "Audio unliked successfully"
	MsgUnlikeFail         = "Failed to unlike audio"
	MsgLikeListOK         = "Liked audios retrieved"
	MsgLikeListFail       = "Failed to fetch liked audios"
	MsgAlreadyLiked       = "Audio already liked"
	MsgLikeNotFound       = "Like not found"

	MsgHistoryListOK      = "Play history retrieved"
	MsgHistoryListFail    = "Failed to fetch play history"
	MsgHistoryDeleteOK    = "History deleted successfully"
	MsgHistoryDeleteFail  = "Failed to delete history"
	MsgHistoryClearOK     = "All history cleared successfully"
	MsgHistoryClearFail   = "Failed to clear history"
	MsgInvalidAudioID     = "Invalid Audio ID"

	MsgLivestreamOK       = "Live stream status"
	MsgLivestreamNoData   = "No data yet"

	MsgDirCreateFail      = "Failed to create directory"
	MsgFileUploadFail     = "Failed to upload image"
)
